# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------

import os
import logging

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Relative sub-directory under each partition's root
_EMBEDDINGS_SUBDIR = "embeddings"
_INDEX_FILENAME = "index.parquet"


def save_embeddings(embeddings: np.ndarray, root_dir: str, partition: str, desc_name: str) -> None:
    """Save embedding matrix to <root_dir>/<partition>_dir/embeddings/<partition>_<desc_name>.npy"""
    out_dir = os.path.join(root_dir, partition + "_dir", _EMBEDDINGS_SUBDIR)
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{partition}_{desc_name}.npy")
    np.save(out_path, embeddings.astype(np.float32))
    logger.info("Saved %s embeddings (%s) to %s.", desc_name, embeddings.shape, out_path)


def load_embeddings_matrix(root_dir: str, partition: str, desc_name: str) -> np.ndarray:
    """Load embedding matrix from the canonical path; returns float32 (n, D)."""
    npy_path = os.path.join(root_dir, partition + "_dir", _EMBEDDINGS_SUBDIR, f"{partition}_{desc_name}.npy")
    if not os.path.isfile(npy_path):
        raise FileNotFoundError(f"Embedding file not found: {npy_path}")
    mat = np.load(npy_path).astype(np.float32)
    logger.info("Loaded %s/%s embeddings: %s.", partition, desc_name, mat.shape)
    return mat


def l2_normalize(embeddings: np.ndarray) -> np.ndarray:
    """Row-wise L2 normalisation; zero vectors are left as-is."""
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
    # Avoid division by zero for zero-magnitude vectors
    norms = np.where(norms == 0.0, 1.0, norms)
    return (embeddings / norms).astype(np.float32)


def cosine_topk(
    query_vec: np.ndarray, ref_matrix: np.ndarray, k: int
) -> tuple[np.ndarray, np.ndarray]:
    """Return top-k cosine similarities and their indices.

    Both query_vec and ref_matrix are assumed to be L2-normalised already,
    so a plain dot product gives cosine similarity.

    Args:
        query_vec:  (D,) float32
        ref_matrix: (n, D) float32
        k:          number of top results to return

    Returns:
        similarities: (k,) float32, descending
        indices:      (k,) int64
    """
    sims = ref_matrix @ query_vec.astype(np.float32)
    k_clamped = min(k, len(sims))
    # argpartition then sort is faster than full argsort for large n
    top_idx = np.argpartition(sims, -k_clamped)[-k_clamped:]
    top_idx = top_idx[np.argsort(sims[top_idx])[::-1]]
    return sims[top_idx], top_idx


def save_index_parquet(df: pd.DataFrame, root_dir: str, partition: str) -> None:
    """Persist the index DataFrame to the canonical parquet location."""
    out_dir = os.path.join(root_dir, partition + "_dir", _EMBEDDINGS_SUBDIR)
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, _INDEX_FILENAME)
    df.to_parquet(out_path, index=False)
    logger.info("Saved %s index parquet (%d rows) to %s.", partition, len(df), out_path)


def load_index_parquet(root_dir: str, partition: str) -> pd.DataFrame:
    """Load the index DataFrame from the canonical parquet location."""
    parquet_path = os.path.join(root_dir, partition + "_dir", _EMBEDDINGS_SUBDIR, _INDEX_FILENAME)
    if not os.path.isfile(parquet_path):
        logger.warning("Index parquet not found: %s — returning empty DataFrame.", parquet_path)
        return pd.DataFrame()
    df = pd.read_parquet(parquet_path)
    logger.info("Loaded %s index parquet: %d rows.", partition, len(df))
    return df


def sanity_check_against_cosmos(
    recomputed: np.ndarray,
    cosmos_vecs: np.ndarray,
    individual_ids: list,
    threshold: float = 0.85,
) -> dict:
    """Compare recomputed embeddings against vectors fetched from Cosmos.

    For each individual, computes the cosine similarity between the
    recomputed embedding and the Cosmos-stored vector.  This is the
    provenance sanity check: if similarity falls below *threshold* we flag
    a mismatch (the Cosmos vector may have been generated by a different
    model or with different preprocessing).

    Args:
        recomputed:     (n, D) float32, L2-normalised recomputed embeddings
        cosmos_vecs:    (n, D) float32, L2-normalised vectors from Cosmos
        individual_ids: list of length n, individual identifier strings
        threshold:      cosine similarity below which a pair is flagged

    Returns:
        dict with keys:
            "mean_cosine"       : float
            "min_cosine"        : float
            "n_below_threshold" : int
            "verdict"           : "ok" | "mismatch"
    """
    if recomputed.shape != cosmos_vecs.shape:
        raise ValueError(
            f"Shape mismatch: recomputed {recomputed.shape} vs cosmos {cosmos_vecs.shape}"
        )

    # Element-wise dot product of paired rows (both assumed L2-normalised)
    cosine_sims = np.sum(recomputed * cosmos_vecs, axis=1)

    mean_cos = float(np.mean(cosine_sims))
    min_cos = float(np.min(cosine_sims))
    n_below = int(np.sum(cosine_sims < threshold))

    flagged = [
        (individual_ids[i], float(cosine_sims[i]))
        for i in range(len(individual_ids))
        if cosine_sims[i] < threshold
    ]

    verdict = "ok" if n_below == 0 else "mismatch"

    logger.info(
        "Cosmos provenance check — mean cosine: %.4f, min cosine: %.4f, "
        "n_below_threshold (%g): %d, verdict: %s",
        mean_cos, min_cos, threshold, n_below, verdict,
    )
    if flagged:
        logger.warning(
            "Individuals below threshold (%g): %s",
            threshold,
            [(iid, f"{sim:.4f}") for iid, sim in flagged],
        )

    return {
        "mean_cosine": mean_cos,
        "min_cosine": min_cos,
        "n_below_threshold": n_below,
        "verdict": verdict,
    }
